# Generated by Django 4.1.7 on 2023-04-07 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_re_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='re_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment'),
        ),
    ]
