# Generated by Django 4.1.7 on 2023-04-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_re_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='re_comment',
            new_name='reply',
        ),
    ]
