# Generated by Django 4.1.7 on 2023-04-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='timetable',
        ),
    ]
