# Generated by Django 4.1.7 on 2023-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_rename_subject_subject_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='place',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
