# Generated by Django 4.1.7 on 2023-04-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_subject_place_alter_subject_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='timetables.timetable'),
        ),
    ]
