# Generated by Django 4.1.7 on 2023-04-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_alter_subject_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
