# Generated by Django 4.1.7 on 2023-04-07 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_friend_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enter_year',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)]),
        ),
    ]
